hostname throbert-router
log stdout

router bgp 65000

router ospf

router isis CORE
# CORE = label pour id le service dans interface/dbug
# isis demande oblig cet arg pas ospf

is-type level-2-only

line vty
# chosit le cli 

